### PR TITLE
Fix parallel execution of the testsuite

### PR DESCRIPTION
**Pull request by coldtobi**
As many of the individual testsuite uses the same output file for the artifacts
of the test suites, the tests are racy if executed in parallel, eg. by ctest
-jxx.  This patch fixes it by assigning individual names for the test artifact
files.

Jira-Issue: LOGCXX-538

### CODE REVIEW

**Comment by coldtobi** [comment]
I need to investigate why the test suite failed. Will reopen PR once ready.

**Comment by coldtobi** [comment]
(Closing nuked the ci logs .... Reopening to get them again....)

**Comment by ams-tschoening** [comment]
Looks like you have simply missed to change `src/test/resources/input/patternLayout13.properties`? I find all the other files changed, but not this one.

**Comment by coldtobi** [comment]
> Looks like you have simply missed to change `src/test/resources/input/patternLayout13.properties`? I find all the other files changed, but not this one.

Good catch!

**Comment by coldtobi** [comment]
The failing testcase on ubuntu-18.04-g++-build-and-test is likely LOGCXX-322 
`2021-12-11T15:44:14.6741094Z 	 20 - multithreadtest (SEGFAULT)`

(I've commented on LOGCXX-322 earlier today)

**Comment by coldtobi** [comment]
@ams-tschoening do you want to take another look or did I miss an open point? (dead lock avoidance)

**Comment by ams-tschoening** [comment]
Things look fine for me and running tests on my system still works. Regarding the [segfault](https://issues.apache.org/jira/browse/LOGCXX-322?focusedCommentId=17457553&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17457553), let's just ignore it for now as part of this PR and merge?

Besides that, [propertiestestcase](https://github.com/apache/logging-log4cxx/pull/79/files#diff-396d775e88c6bc937d2b1ec27fc826fecdfe42eaaec8f3253089e93f96d787c9) is changed here and in [PR #85](https://github.com/apache/logging-log4cxx/pull/85/commits/9bf4d0f752a2d1b15247cc6fc0266fc9efaa49f0), resulting in a conflict most likely. Any preference about which one to merge first? I would simply do this one and adopt the other PR.

**Comment by coldtobi** [comment]
I've got no preferences about the merge order, so just do as you see fit.
thanks foor looking into it!

**Pull request merged**
