### PR TITLE
Add support for building log4cxx as a statically linked library on Windows

### PR DESCRIPTION
**Pull request by stephen-webb**
Replacement for PR #20

### CODE REVIEW

**Comment by ams-tschoening** [comment]
Any reason why `-DAPU_STATIC` and `-DAPR_STATIC` are not documented with something like `=off|on` , like `-DBUILD_SHARED_LIBS` is? Does this work differently or ...?

**Comment by stephen-webb** [comment]
No, they work the same, except the Build shared is on by default. The =on
does no more than the existence of a definition.

**Comment by stephen-webb** [comment]
Correction, =yes is equivalent to existence of a definition

**Comment by ams-tschoening** [comment]
Then please add `=yes|no|on|off` as necessary/useful for `-D*_STATIC`, so that its in line with the other documented options. Afterwards I'm going to merge.

**Pull request merged**
