### PR TITLE
Flush at exit

### PR DESCRIPTION
**Pull request by vopl**
Flushing all buffered data during the static deinitialization phase.

### CODE REVIEW

**Comment by rm5248** [comment]
Shouldn't `LogManager::shutdown` do the proper flushing of data?  Or does that not work under certain situations?

**Comment by vopl** [comment]
> Shouldn't `LogManager::shutdown` do the proper flushing of data? Or does that not work under certain situations?

`LogManager::shutdown` terminates logger functionality, but this case about events-at-exit, in which all logger functionality should continue to work

**Comment by swebb2066** [comment]
Perhaps you also could include SocketOutputStream and ODBCAppender?

**Comment by vopl** [comment]
I can't support SocketOutputStream, it doesn't have enough internal infrastructure for flushing, in particular, there is no  apr-Pool instance, which is placed in more derived types. (It's not actually used for flushing, but I don't able to make a second layer of stubs)

**Comment by swebb2066** [comment]
> I can't support SocketOutputStream
OK, but as XMLSocketAppender calls flush() in each append(), I suggest the change [XMLSocketAppender](https://github.com/apache/logging-log4cxx/pull/281/commits/876763f1a06781a19dbca5f1a767f838c932a078) is not required.

**Pull request merged**
