### PR TITLE
Add support for building and testing with cmake

### PR DESCRIPTION
**Pull request by swebb2066**
This just adds CMakeLists.txt files to various directories. No existing files are changed

### CODE REVIEW

**Comment by ams-tschoening** [comment]
Thanks for the contribution, but I'm not sure how to deal with this currently and simply leave it open until further decisions. Some links to earlier discussions about that topic:

https://github.com/apache/logging-log4cxx/pull/2#issuecomment-370781162
https://github.com/apache/logging-log4cxx/pull/3#issuecomment-356979649

**Comment by swebb2066** [comment]
To enable inclusion by vcpkg, log4cxx needs a modern cmake build system. I can see no problem having an one more way to build log4cxx. If there is some support I will add documentation etc.

**Comment by jvz** [comment]
Can anything from this be combined with #14? I love the simplification if possible rather than supporting multiple build systems.

**Comment by ams-tschoening** [comment]
From my understanding this is CMAKE without removing anything, while #14 is CMAKE with removing at least ANT, because in the past it has been discussed several times to focus on one build system only. So it's either about adding #12 or #14, not both I guess, with the latter making more sense in the long term anyway.

While we are at it, it should be discussed if CMAKE should replace Autotools on Linux as well, leaving only the ANT/MAVEN-parts in place necessary for generating the site, optionally release handling itself and stuff. Though especially the latter seems pretty complicated to me as well, but I'm not that familiar with MVN-releases.

**Comment by jvz** [comment]
> While we are at it, it should be discussed if CMAKE should replace Autotools on Linux as well, leaving only the ANT/MAVEN-parts in place necessary for generating the site, optionally release handling itself and stuff. Though especially the latter seems pretty complicated to me as well, but I'm not that familiar with MVN-releases.

I like that idea.

**Comment by rm5248** [comment]
Why use Maven at all at that point?  What I do for C++ projects is to just generate the site with Doxygen; it's possible to then make a doc/ subfolder that has the files in markdown or asciidoc([example](https://github.com/dbus-cxx/dbus-cxx/tree/7e48c593330a0b3bf9d576b8a35e4b74b944f602/doc)).  The style is different, but it would integrate nicely with the build process.

**Comment by ams-tschoening** [comment]
> Why use Maven at all at that point? What I do for C++ projects is to just generate the site with Doxygen;[...]

Maven has been used for release-handling and site generation. Doxygen is used for apidocs as well already, but not for other parts of the site, like changes-reports and all that stuff.

**Comment by ams-tschoening** [comment]
It currently looks like #14 gets merged, so I'm closing here for now.

**Pull request closed without merging**
