### PR TITLE
Fix SMTP appender

### PR DESCRIPTION
**Pull request by swebb2066**
The SMTP appender has probably not been used since verion 0.10 (if it ever has).

There is a new release of libesmtp (maybe partly because log4cxx is listed as user - see the [user list](https://github.com/libesmtp/libESMTP/issues/2) )

### CODE REVIEW

**Comment by rm5248** [comment]
Looks good to me.  Did you actually use it to send an email?

**Comment by swebb2066** [comment]
Not yet - I will try sending an email today.

**Comment by swebb2066** [comment]
I have not successfully sent a mail to smtp.gmail.com or to my internet provider. Perhaps they all need Secure Socket Layer (SSL) and Transport Layer Security (TLS) protocols now.

**Comment by rm5248** [comment]
The google documentation does imply that you need to have [SSL/TLS enabled](https://support.google.com/mail/answer/7126229?hl=en#zippy=%2Csecurity-certificate-cn-error%2Cstep-change-smtp-other-settings-in-your-email-client), perhaps that is causing the issue?

**Comment by swebb2066** [comment]
I am now able to send a mail message using my local internet provider SMTP server and port 587.

I had to build libESMTP with -Dtsl=enabled (after installing libssh-dev).

**Pull request merged**
