### PR TITLE
MapFilter documentation in Markdown

### PR DESCRIPTION
**Pull request by pm-cfs**
Documentation for MapFilter was requested, but I couldn't reconcile the various format/location suggestions, so I'm providing this in Markdown which should be straightforward to convert to whatever final format is decided. It seemed better to have the documentation than not and I didn't want to accidentally lose it.

### CODE REVIEW

**Review by ams-tschoening — CHANGES_REQUESTED** [review]
I would prefer backticks instead of italic for "code", which would avoid using `_[...]_` and `*[...]*` as well. Additionally and unless done for a special reason, I would prefer a code block like the following for the XML-examples as well. This should even keep newlines when rendered, so `<br/>` could be removed?

    ```xml
    [...]
    ```

We should keep in mind that code and XML have a semantic meaning and should be declared as such in Markdown, not only visibly formatted.

**Comment by pm-cfs** [comment]
Requested changes made; my markdown engine doesn't do a great job with this, but that's my problem. I understand the semantics request and hopefully this works better for everyone - viewing & copy/paste.

**Review by ams-tschoening — APPROVED** [review]
Didn't know I could implement changes on my own, so have done that now. Please review for you again, if you can live with my changes.

**Comment by pm-cfs** [comment]
I'm ok with these; I would note that the tabs are a visibility thing for non-markdown and/or compatibility for some renderers that use them.
I didn't notice that my editor removed the indentions; that's definitely good for everyone.

**Review by rm5248 — APPROVED** [review]

**Pull request merged**
