### PR TITLE
Remove CFString support

### PR DESCRIPTION
**Pull request by swebb2066**
The original commit by Curt Arnold was 2007 (b0ce6ef31). It has not been compiled since 0.10.0.

### CODE REVIEW

**Comment by rm5248** [comment]
Maybe it worked originally?  The API may have changed since 2007.

I don't feel comfortable removing a feature that should work without a major bump in the ABI though, since if we remove the CFString methods that is an ABI-breaking change(at least on OSX).

**Comment by swebb2066** [comment]
OK, it stays

**Comment by swebb2066** [comment]
I cannot see how to make CFString compile on OSX.

Any suggestions?

**Comment by swebb2066** [comment]
It seems it is std::basic_string<UniChar> that is not supported.

**Pull request closed without merging**
